#!/usr/bin/csh

cd database
foreach file (*.cfg)
  set dst = {$file:r}.old
  #echo $file
  cp -f $file $dst
  sed '5 s/vrenkens/hvanhamm/' < $dst | sed '11 s/vrenkens/hvanhamm/' > $file
  rm -f $dst
end
